language: php
php:
  - 5.3
before_script:
  - composer self-update
  - composer install
  - phpenv rehash
script:
  - vendor/bin/phpunit -v --colors --coverage-text
notifications:
  email:
    - artodeto@arcor.de
sudo: false
