language: php
php:
  - 5.3
before_script:
  - composer self-update
  - composer install --dev
  - phpenv rehash
script: phpunit -v --colors --coverage-text
notifications:
  email:
    - artodeto@arcor.de
